name: maestro-manifest-repository

on:
  workflow_dispatch: ~
  push:
    branches:
      - master
      - main

jobs:
  apply_changes:
    uses: nodis-com-br/gha_maestro-apply-changes@master
    with:
      openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
      vault_addr: ${{ secrets.VAULT_ADDR }}
      vault_approle_role_id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault_approle_secret_id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
      pypi_addr: ${{ secrets.PYPI_ADDR }}