name: reactjs-app

on:
  workflow_dispatch: ~
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  get_metadata:
    uses: nodis-com-br/gha-workflows/.github/workflows/get-metadata.yaml@master
  test_code:
    uses: nodis-com-br/gha-workflows/.github/workflows/testing.yaml@master
    needs:
      - get_metadata
    secrets:
      openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
      vault_addr: ${{ secrets.VAULT_ADDR }}
      vault_approle_role_id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault_approle_secret_id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
  build_artifact:
    uses: nodis-com-br/gha-workflows/.github/workflows/publish-reactjs-app.yaml@master
    with:
      nodejs_version: '16.10.0'
    needs:
      - get_metadata
  deploy_artifact:
    uses: nodis-com-br/gha-workflows/.github/workflows/deploy-static-site.yaml@master
    needs:
      - build_artifact
    secrets:
      openvpn_config: ${{ secrets.OPENVPN_CONFIG }}
      vault_addr: ${{ secrets.VAULT_ADDR }}
      vault_approle_role_id: ${{ secrets.VAULT_APPROLE_ROLE_ID }}
      vault_approle_secret_id: ${{ secrets.VAULT_APPROLE_SECRET_ID }}
  revert_bump:
    uses: nodis-com-br/gha-workflows/.github/workflows/revert-bump.yaml@master
    needs:
      - build_artifact
    if: always()
    with:
      build_result: ${{ needs.build_artifact.result }}