name: publish-reactjs-webapp

on:
  workflow_call:
    inputs:
      nodejs_version:
        type: string
        description: ''
        required: false
        default: '15.14.0'
  
jobs:
  publish_reactjs_webapp:
    runs-on: ubuntu-latest
    if: contains('push workflow_dispatch', github.event_name) && !contains(github.event.head_commit.message, 'skip_ci') && !contains(github.event.head_commit.message, 'skip_build')
    steps:
      - run: env | sort
      - name: Checkout repository
        uses: actions/checkout@main
        if: ${{ !contains(github.event.head_commit.message, 'skip_build') }}
        with:
          ref: ${{ github.ref }}
      - name: Load project metadata to environment variables
        uses: nodis-com-br/gha_metadata-load@master
      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.nodejs_version }}
      - name: Build artifact
        shell: bash
        run: |
          source env-${NODIS_DEPLOY_ENVIRONMENT}.sh || echo "env-${NODIS_DEPLOY_ENVIRONMENT}.sh not found"
          yarn install --prod
          yarn build
          echo ${NODIS_PROJECT_VERSION} > build/version.txt
          tar czvf ${NODIS_ARTIFACT_FILENAME} build
        env:
          NPM_TOKEN: ${{ github.token }}
      - name: Upload artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ${{ env.NODIS_ARTIFACT_FILENAME }}
          tag: v${{ env.NODIS_PROJECT_VERSION }}