name: publish-python-package

on:
  workflow_call:
    secrets:
      pypi_addr:
        description: ''
        required: true
        
jobs:
  publish_python_package:
    runs-on: ubuntu-latest
    if: contains('push workflow_dispatch', github.event_name) && !contains(github.event.head_commit.message, 'skip_ci')
    steps:
      - run: env | sort
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
      - name: Load project metadata to environment variables
        uses: nodis-com-br/gha-metadata-load@master
      - run: pip3 install twine
        shell: bash
      - name: Build artifact
        run: python3 setup.py sdist && echo "NODIS_ARTIFACT_FILENAME=$(ls dist)" >> $GITHUB_ENV
        shell: bash
      - name: Upload artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: dist/${{ env.NODIS_ARTIFACT_FILENAME }}
          tag: v${{ env.NODIS_PROJECT_VERSION }}
      - name: Upload artifact to repository
        run: python3 -m twine upload dist/* --verbose
        shell: bash
        env:
          TWINE_USERNAME: ${{ env.NODIS_REPOSITORY_NAME }}
          TWINE_PASSWORD: ${{ github.token }}
          TWINE_REPOSITORY_URL: ${{ secrets.pypi_addr }}