name: publish-helm-chart

on:
  workflow_call:
    secrets:
      charts_addr:
        description: ''
        required: true


jobs:
  publish_chart:
    runs-on: ubuntu-latest
    if: contains('push workflow_dispatch', github.event_name) && !contains(github.event.head_commit.message, 'skip_ci')
    steps:
      - run: env | sort
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
      - name: Load project metadata to environment variables
        uses: nodis-com-br/gha_metadata-load@master
      - name: Add chart repository and build dependencies
        run: |
          helm repo add nodis https://${NODIS_REPOSITORY_NAME}:${{ github.token }}@${{ secrets.charts_addr }}
          helm repo update
          helm dependencies up
        shell: bash
      - name: Validate chart
        run: helm template --debug . > /dev/null
        if: ${{ env.NODIS_CHART_TYPE == 'application' }}
        shell: bash
      - name: Build chart
        run: helm package .
        shell: bash
      - name: Publish chart to repository
        run: curl --data-binary "@${NODIS_ARTIFACT_NAME}" https://${NODIS_REPOSITORY_NAME}:${{ github.token }}@${{ secrets.charts_addr }}/api/charts
        shell: bash
      - name: Upload chart to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: ${{ env.NODIS_ARTIFACT_NAME }}
          tag: v${{ env.NODIS_PROJECT_VERSION }}