name: publish-docker-image

on:
  workflow_call:
  
jobs:
  publish_public_image:
    runs-on: ubuntu-latest
    if: contains('push workflow_dispatch', github.event_name) && !contains(github.event.head_commit.message, 'skip_ci')
    steps:
      - run: env | sort
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}
      - name: Load project metadata to environment variables
        uses: nodis-com-br/gha_metadata-load@master
      - name: Build and push docker image
        uses: nodis-com-br/gha_docker-publish-image@master