name: terraform-plan

on:
  workflow_call:
    secrets:
      openvpn_config:
        description: ''
        required: true
      vault_addr:
        description: ''
        required: true
      vault_approle_role_id:
        description: ''
        required: true
      vault_approle_secret_id:
        description: ''
        required: true
      vault_gcp_roleset_path:
        description: ''
        required: true
    inputs:
      vault_tf_modules_key_path:
        required: false
        type: string
        default: secret/data/ssh/tf_modules
      vault_gcp_roleset_path:
        required: false
        type: string
        default: gcp/terraform/roleset/terraform-states/token
    outputs:
      plan_exit_code:
        description: ''
        value: ${{ jobs.terraform_build_plan.outputs.plan_exit_code }}
        
jobs:
  terraform_build_plan:
    runs-on: ubuntu-latest
    if: contains('push workflow_dispatch', github.event_name) && !contains(github.event.head_commit.message, 'skip_ci')
    env:
      VAULT_ADDR: ${{ secrets.vault_addr }}
      TERRAFORM_VERSION: 1.0.11
    outputs:
      plan_exit_code: ${{ steps.plan.outputs.exitcode }}
    steps:
      - run: env | sort
      - uses: actions/checkout@main
        name: Checkout repository
        with:
          fetch-depth: 20
      - name: Setup Terraform
        uses: nodis-com-br/gha-terraform-setup@master
        with:
          openvpn_config: ${{ secrets.openvpn_config }}
          vault_addr: ${{ secrets.vault_addr }}
          vault_approle_role_id: ${{ secrets.vault_approle_role_id }}
          vault_approle_secret_id: ${{ secrets.vault_approle_secret_id }}
      - name: Build Terraform plan
        id: plan
        run: terraform plan -out=plan -input=false -detailed-exitcode
        shell: bash
      - name: Break workflow if plan has failed
        if: steps.plan.outputs.exitcode == '1'
        run: exit 1
        shell: bash
      - name: Save plan to artifact
        if: steps.plan.outputs.exitcode == '2'
        uses: actions/upload-artifact@v2
        with:
          name: plan
          path: plan
          retention-days: 1